[project]
name = "beaver-db"
version = "0.16.3"
description = "Fast, embedded, and multi-modal DB based on SQLite for AI-powered applications."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.12.0",
    "numpy>=2.3.3",
]
classifiers = [
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[tool.hatch.build.targets.wheel]
packages = ["beaver"]

[dependency-groups]
dev = [
    "textual>=6.1.0",
]
