[project]
name = "beaver-db"
version = "0.5.2"
description = "Fast, embedded, and multi-modal DB based on SQLite for AI-powered applications."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.3",
    "scipy>=1.16.2",
]

[tool.hatch.build.targets.wheel]
packages = ["beaver"]
