[project]
name = "beaver-db"
version = "0.18.3"
description = "Fast, embedded, and multi-modal DB based on SQLite for AI-powered applications."
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
]

[project.scripts]
beaver = "beaver.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["beaver"]

[project.optional-dependencies]
vector = ["faiss-cpu>=1.12.0"]
server = ["fastapi[standard]>=0.118.0"]
cli = ["typer>=0.19.2", "fire[cli]>=0.7.1"]
full = ["beaver-db[server]", "beaver-db[vector]", "beaver-db[cli]"]

[dependency-groups]
dev = ["textual>=6.1.0"]
